name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Tidy Go Modules
        run: go mod tidy

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/master:1.9 .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push Docker Image to Repository
        run: |
          docker push ${{ secrets.DOCKER_USER }}/master:1.9
